---
title: "GraphQLのエラーハンドリング"
emoji: "🗂"
type: "tech" # tech: 技術記事 / idea: アイデア
topics: ["GraphQL", "Rails", "Next.js"]
published: false
---

Rails × [GraphQL Ruby](https://graphql-ruby.org/) で作ったクエリを、フロントで呼び出す際に、エラーハンドリングでうまくいかないケースがありました。
その際に調べた内容をまとめておきます。

## 環境

- Ruby v3.2.2
- Rails v7.0.5
- React v18.2.0
- Next.js v13.0.7
- Heroku
- GraphQL Ruby v1.8

## うまくいかなかったケース

元々は、クエリを叩いた際に、バックエンド側で何かエラーが発生した際のエラーハンドリングを下記のように実装していました。

```javascript
      searchUsers({
        variables: {
          ...
        },
      })
        .then((response) => {
          resolve()
        })
        .catch(() => {
          reject()
        })
```

エラー発生時には catch を通る想定です。
500 エラーなど基本的にはこの書き方で問題なかったのですが、Heroku のタイムアウト時のエラー(H12 エラー)をキャッチしようとしたところ、catch ではなく then を通っていました。

そこで下記のように修正しました。
then の中で、レスポンスに error が含まれているかを判断し、含まれている場合は reject()する形です。

```javascript
      searchUsers({
        variables: {
          ...
        },
      })
        .then((response) => {
          if (response.error) {
            reject()
          }
          resolve()
        })
        .catch(() => {
          reject()
        })
```

## なぜ、うまくいかなかったか。

試しに REST で試してみたところ、Heroku のタイムアウト時も catch()で拾えていたので、GraphQL 独自の仕様のようです。
そこで Heroku のタイムアウト時のレスポンスと、バックエンド側で 500 エラーが発生した場合のレスポンスを比較してみました。

Hroku のタイムアウト時は下記の画像のように、Response Headers/Content-Type が html 形式になっています。
html 形式で返ってきた場合、JS で catch できないようです。

一方でバックエンド側のエラーの場合、

GraphQL のエラーについては下記の記事を参考にさせていただきました。
感謝！！
https://zenn.dev/konboi/articles/89263019f68781

## そもそも

GraphQL のドキュメントにもあるように、HTTP のレスポンスコードは 200（Success）のまま、レスポンス Body のエラーコードでエラーの詳細を表現する方法が推奨されているため、then の中でもエラーをキャッチするようにしておくべきでした。
https://www.apollographql.com/docs/apollo-server/data/errors/#returning-http-status-codes

以上、です。
